config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :recipes, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create, :index]
  end

  get '/random', to: 'recipes#random'
  get 'recipes/:id/instruction', to: 'recipes#instruction', as: :instruction
  get '/accountsummary', to: 'recipes#accountsummary'
  get 'recipes/:id/order', to: 'recipes#order', as: :order
  get 'recipes/:id/order/thankyou', to: 'recipes#thankyou', as: :thankyou
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :recipe_category
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :portions, dependent: :destroy
  validates :name, uniqueness: true


end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
end

app/models/list_recipe.rb
class ListRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :list
end

app/models/portion.rb
class Portion < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :recipe_categories, dependent: :destroy
  has_many :categories, through: :recipe_categories
  has_many_attached :images
  has_many :portions, dependent: :destroy
end

app/models/recipe_category.rb
class RecipeCategory < ApplicationRecord
  belongs_to :recipe
  belongs_to :category
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :recipe
  belongs_to :user

  validates :description, :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home

  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :random ]

  def index
  	@recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  

    @review = Review.where(recipe_id: @recipe.id)
    @portions = Portion.where(recipe_id: @recipe.id)

  end

  def random
    #Old logic for picking random recipes
    #@recipe = Recipe.all.shuffle[0]
    @recipe = Recipe.all.sample
    

    if params[:vegan]
      @recipe = Recipe.where(vegan: true).sample
    end

    if params[:vegetarian]
      @recipe = Recipe.where(vegetarian: true).sample
    end

    if params[:gluten_free]
      @recipe = Recipe.where(gluten_free: true).sample
    end

    if params[:dairy_free]
      @recipe = Recipe.where(dairy_free: true).sample
    end

    if params[:ketogenic]
      @recipe = Recipe.where(ketogenic: true).sample
    end
    
    

    redirect_to recipe_path(@recipe, params.permit(params.keys).to_h)
    
  end

  def new
    @recipe = Recipe.new
  end

  def create
  	@recipe = Recipe.new(recipe_params)
  	@recipe.user = current_user
  	@recipe.save
  end

  def instruction
  	@recipe = Recipe.find(params[:id])
    @portions = Portion.where(recipe_id: @recipe.id)     
	end

  def order
    params.permit!  
  	@recipe = Recipe.find(params[:id])
    @portions = Portion.where(recipe_id: @recipe.id)
    
    selected_ingredients = params.to_h.filter do |key,value|
      key.start_with?('ingredient_')
    end
    
    # Ingredients selected by the user
    temp = (selected_ingredients.map {|ingredient, _| ingredient.gsub('ingredient_', '')}).map(&:to_i)
    
    
    # Ingredients which are part of the Recipe#Portion
    @actual_ingredients = @portions.map do |portion|
      portion.ingredient.id
    end

    # Ingredients which have to be ordered
    #@ingredients_to_order = @actual_ingredients.reject{|ingredient| temp.include?(id:)}

    ingredients_to_order = @actual_ingredients.reject {|ingredient| temp.include?(ingredient)}
    
    # instantiate a Variable so as to be used in order.html.erb
    @ingredients = Ingredient.where(id: ingredients_to_order)

    total = @ingredients.reduce(0) { |sum, ingredient| sum + ingredient.price }
    @total = total
    



  end

  def thankyou

  end

  def accountsummary

  end

  


  private

  def recipe_params
    params.require(:recipe).permit(:title, :instructions, :prep_time, :vegetarian, :vegan, :gluten_free, :dairy_free, :very_healthy, :ketogenic, :servings, :source_id, :summary, images: [])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!
    
    def new
        @recipe = Recipe.find(params[:recipe_id])
        @review = Review.new
    end

    def create
      
      @recipe = Recipe.find(params[:recipe_id])
      @review = Review.new(review_params)
      @review.user = current_user
      @review.recipe = @recipe
      @review.save
      redirect_to recipe_reviews_path(@recipe)
    end

    def index
      @recipe = Recipe.find(params[:recipe_id])
      @reviews = @recipe.reviews
    end



    private

  def review_params
    params.require(:review).permit(:description, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>eatsy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag(source = "favicon-32x32.png") %>    
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>


    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
  </head>
  <body>
    <div id="main-content">
    <%= yield %>
    <%= render 'shared/flashes' %>
    </div>
    <%= render 'shared/navbar' %>
  </body>
</html>

app/views/pages/home.html.erb
<header class="masthead text-white text-center d-flex justify-content-center align-items-center flex-column">
  <%=image_tag("logo-eatsy.png")%>
          <!-- <div class="overlay"></div> -->
  <% if user_signed_in? %>
    <%= link_to "eat simple", recipes_path, class: "btn btn-lg btn-warning call-to-action" %>
  <% else %>
    <%= link_to "eat simple", random_path(@recipe), class: "btn btn-lg btn-warning call-to-action" %>
  <% end %>

</header>

app/views/recipes/_details.html.erb
<p class="recipe-instructions"><b>Summary : </b><%= recipe.summary.html_safe %></p>

app/views/recipes/_ingredient_selection.html.erb
<div class="" role="document">
	<div class="">
  	<div class="card-body text-center">
      <% portions.each do |portion| %>
				<div class="row">
					<div class="col	">
						<input type="checkbox" class="Accept" name="ingredient_<%= portion.ingredient.id%>" aria-label="ingredientSelection">
					</div>
					<div class="col">
						<h6><%= portion.ingredient.name %> </h6>
				  </div>
					<div class="col"> <%= portion.amount.to_f.round(2) %> </div>

					<div class="col"> <%= portion.unit %></div>
				</div>
			<% end %>
      <div class="row">
        <div class="col-3 ">
          <input type="checkbox" name="select-all" id="select-all">
        </div>
        <div class="col-3">
          <strong> Select all</strong>
        </div>
      </div>
		</div>
	</div>
</div>

app/views/recipes/accountsummary.html.erb
<div class="col-lg-6 col-sm-6">
    <div class="card hovercard">
        <div class="card-background">
            <img class="card-bkimg" alt="" src="https://images.unsplash.com/photo-1493770348161-369560ae357d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80">
            <!-- http://lorempixel.com/850/280/people/9/ -->
        </div>
        <div class="useravatar">
            <img alt="" src="https://avatars3.githubusercontent.com/u/64709573?v=4">
        </div>
        <div class="card-info"> <span class="card-title">Gonzalo Carrillo</span>
        </div>
    </div>

        <div class="well">
      <div class="tab-content">
        <div class="tab-pane fade in active text-center" id="tab1">
          <h3>eatsy member</h3>
            <p>Start date: June 1, 2020</p>
        </div>

      </div>
    </div>

    </div>

app/views/recipes/index.html.erb
<div class="img-index">
  <div class="dietary-chekbox vertical-center ">
   	<div class="card-body">
      <form action="<%= random_path%>">
     
        <div class="form-group ">
          <label class="control-label">
            <h3>Choose your diet</h3>
          </label>
          <div class="checkbox">
            <label class="checkbox">
            <input name="vegan" type="checkbox" value="true"/>
            Vegan
            </label>
          </div>
          <div class="checkbox">
            <label class="checkbox">
            <input name="vegetarian" type="checkbox" value="true"/>
            Vegetarian
            </label>
            </div>
          <div class="checkbox">
            <label class="checkbox">
            <input name="gluten_free" type="checkbox" value="true" disabled/>
            Gluten Free
            </label>
          </div>
          <div class="checkbox">
            <label class="checkbox">
            <input name="dairy_free" type="checkbox" value="true" disabled/>
            Diary Free
            </label>
          </div>
          <div class="checkbox">
            <label class="checkbox">
            <input name="ketogenic" type="checkbox" value="true" disabled/>
            Ketogenic
            </label>
          </div>
        </div>
        <div class="form-group">
          <div>
          <button class="btn btn-warning " name="submit" type="submit">
            eat simple
          </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/recipes/instruction.html.erb
<div class="img-index4"></div>
  <div class="" role="document">
    <div class="text-white">
      <div class="card-body">
        <h3>Ingredients:</h3>
        <div class="col 4">
          <% @portions.each do |portion| %>
          <%= portion.amount.to_f.round(1) %> <%= portion.unit %>
          <%= portion.ingredient.name %><span>,</span>
        <% end %>
      </div>
    </div>
  </div>

<div class="" role="document">
  <div class="text-white">
    <div class="card-body">
      <div class="" id="Nutrients">
        <h3>Nutrients:</h3>
      </div>
      <div class="col-4">
        <p>Calories :<%=@recipe.calories%> </p>
        <p>Carbs :<%=@recipe.carbs%>g </p>
        <p>Fat :<%=@recipe.fat%>g </p>
        <p>Protein :<%=@recipe.protein%>g </p>
      </div>
    </div>
  </div>
</div>
<div class="" role="document">
  <div class="text-white">
    <div class="card-body">
      <h3>Instructions:</h3>
      <div class="col-12">
        <%=@recipe.instructions.html_safe%>
      </div>
    </div>
  </div>
</div>
<div class=" button-navbar d-flex align-items-center justify-content-center"style="margin-top: 5%;">
  <%= link_to new_recipe_review_path(@recipe) do %>
    <button class="add-to-cart btn-lg btn-warning" type="button">Rate Now</button>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="container">
	<div class="card">
		<div class="container-fliud">
			<div class="wrapper row">
				<div class="preview col-md-8">
          <h3> Input Information </h3>
          <%= simple_form_for @recipe do |r| %>
            <%= r.input :title %>
            <%= r.input :instructions %>
            <%= r.input :prep_time %>
            <%= r.input :servings %>
            <%= r.input :summary %>
            <!-- <%= r.input :photos, as: :file, input_html: { multiple: true } %> -->
            <%= r.button :submit, class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>   

app/views/recipes/order.html.erb
<link rel="stylesheet" type="text/css" href="show.css" />

<div class="container" role="document">

	<div class="">
  	<div class="card-body text-center">
			<div class="header">
        <h3>Order Summary</h3>
      </div><br><br>
        <% @ingredients.each do |ingredient| %>
        <div class="row">
          <div class="col text-left"><%= ingredient.name %></div>
            <div class="col text-right">$ <%= ingredient.price %></div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="container" role="document">
	<div class="">
  	<div class="card-body text-center">
			 <div class="row lower">
          <div class="col text-left">Subtotal</div>

          <div class="col text-right">$&nbsp;<%= @total.round(2) %></div>
        </div>
        <div class="row lower">
          <div class="col text-left">2-hour delivery</div>
          <div class="col text-right">Free</div>
        </div>
        <div class="row lower">
          <div class="col text-left"><b>Total</b></div>

          <div class="col text-right">$&nbsp;<b><%= @total.round(2) %></b></div>

        </div>
    </div>
  </div>
</div>
<div class="" role="document">
	<div class="">
  	<div class="card-body text-center">
      <div class="header">
        <h3>Payment Details</h3>
      </div>
        <div class="row item">
          <div class="col-12">
            <div class="img-container">
                <img src="https://img.icons8.com/color/48/000000/visa.png" /> <img src="https://img.icons8.com/color/48/000000/mastercard-logo.png" />  <img src="https://api.iconify.design/logos:discover.svg?width=50&height=25" />  <img src="https://api.iconify.design/logos:apple-pay.svg?width=50&height=25" /></div>
            </div>
          </div>
        </div>
        <form>
          <div class="card-body text-center">
            <div class="row lower">
              <div class="col text-left"> <span>Cardholder's name:</span> </div>
              <div class="col text-right"><input placeholder="Linda Williams"></div> <br><br>
            </div>
            <div class="row lower">
              <div class="col text-left"> <span>Card Number:</span> </span> </div>
              <div class="col text-right"><input placeholder="0125 6780 4567 9909"> <br><br></div> <br><br>
            </div>
            <div class="row lower">
              <div class="col text-left"> <span>Expiration date:</span> </span> </div>
              <div class="col text-right"><input placeholder="YY/MM"></div> <br><br>
            </div>
            <div class="row lower">
                <div class="col text-left"> <span>CVV:</span> </div>
                <div class="col text-right"><input placeholder="823" id="cvv"> </div> <br><br>
            </div>
          </div>
        </form>
      </div>
      </div>
  </div>
</div>
<div class="button-navbar d-flex justify-content-center align-items-center">
<%= link_to "Place Order", thankyou_path, class: "btn btn-lg btn-warning"%>
</div>

app/views/recipes/random.html.erb
<div class="container">

	<div class="container">
		<div class="row bg-light">
     	<img src=<%= @recipe.image %>
			 <h1><%= @recipe.title %></h1>
  	</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col bg-primary"><%= @recipe.servings %></div>
			<div class="col bg-primary"><%= @recipe.prep_time %></div>
			<div class="col bg-primary">Review</div>
		</div>
		<div class="row">
			<div class="col">
			<%= render 'details', recipe: @recipe %>
	
			</div>	
					
		</div>

		<div class="row">
			<div class="col btn btn-primary">Sign Up</div>
		</div>
</div>

app/views/recipes/show.html.erb
<!-- app/views/offers/show.html.erb -->
<%# <% content_for :meta_title, "#{@recipe.title} is on #{DEFAULT_META["meta_product_name"]}" %>
<%# <% content_for :meta_description, @recipe.summary.html_safe %>
<%# <% content_for :meta_image, recipe_path(@recipe.image) %>


<div class="container-fluid">
  <div class="row mx-auto">
     <div class="img_position" style=" margin-top: 20px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= @recipe.image %>')">
      <h3 class="text-center font-weight-lighter text-align-justify"><%= @recipe.title %></h3>
    </div>
  </div>


  <div class="container">
    <div class="row card-body text-center">
      <div class="col">
        <p class="recipe_attrs"><%= image_tag "https://api.iconify.design/emojione-monotone:pot-of-food.svg?color=orange&width=50&height=25" %><%=@recipe.servings%></p>
      </div>
      <div class="col">
        <p class="recipe_attrs"><%= image_tag "https://api.iconify.design/whh:microwave.svg?color=orange&width=50&height=25" %><%= @recipe.prep_time %> min</p>
      </div>
      <div class="col">
        <p class="recipe_attrs"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><a style="text-decoration: none;">Rating</a></p>
      </div>
    </div>
      <div class= "row" style="padding-left: 10px;">
        <div class=" text-center col">
          <%= link_to "Next recipe", random_path(@recipe, params.permit(params.keys).to_h), class: "btn-sm btn btn-warning" %>
        </div>
        <div class=" text-center col">
          <%= link_to "View reviews", recipe_reviews_path(@recipe), class: "btn-sm btn btn-warning" %>
        </div>
      </div>

    <h5 id="cat-ingredients">What ingredients do you have?</h5>
		<form action="<%=order_path%>">
			<input type="hidden" name="recipe_id" value="<%=@recipe.id%>">


			<% if user_signed_in? %>
      	<%= render 'ingredient_selection', portions: @portions %>
    	<% else %>
      	<%= render 'details', recipe: @recipe %>
    	<% end %>





		    <div style="height: 50px" class=" button-navbar d-flex align-items-center justify-content-center">
				  <%= link_to "Cook Now", instruction_path, class: "btn btn-lg btn-warning", id: "cook-now-button" %>
					<button type="submit" class="btn btn-lg btn-warning" id="order-now-button">
						Order Now
          </button>
       </div>
		</form>
	</div>
</div>

app/views/recipes/thankyou.html.erb
<div class="" role="document">
  <div class="img-index2">
    <div class="card-body text-center">
      <div class="checkout text-format text-center">
        <img src=" https://i.imgur.com/d2dKtI7.png" height="100" width="100">
          <h3>Thanks for your order! </h3>
            <h4>It will arrive within 2 hours!</h4>
              <div class="checkout2">
                <%= link_to "e a t s y", recipes_path, class: "btn btn-lg btn-warning"%>
              </div>
      </div>
    </div>
  </div>
</div>

app/views/reviews/index.html.erb
<div class="container text-center">
  <div class="">
    <div><img class="image-reviews"style="margin-top: 20px;" src='<%= @recipe.image %>'>
       <h4 class="font-weight-bold"><%=@recipe.title%></h4>
      <div class="line"></div>
        <div class="">
        <h5 class="text-secondary">Ratings</h5>
        </div>
      </div>
      <% @reviews.each do |review| %>
      <div class="">
        <div class="">
        <%review.rating.times do %>
        <i class="fas fa-star"></i>
        <%end%>
       <h5 class="text-secondary">Feedback</h5>
      <div class="">
      </div>
      <h7 class="rating"><%=review.description%></h7>
        </div>
      </div>
      <% end %>
  </div>
</div>

  <div class= "text-center" style="margin-top: 10%;">
    <%= link_to "Next Recipe", root_path, class: "btn btn-lg btn-warning" %>
  </div>

app/views/reviews/new.html.erb
<div class="" role="document">
  <div class="img-index3">
    <div class="card-body text-center">
      <div class="checkout text-format text-center">
        <img src=" https://i.imgur.com/d2dKtI7.png" height="100" width="100">
        <h3>
          Add a comment
        </h3>
          <%= simple_form_for [ @recipe, @review ] do |f| %>
            <%= f.input :description, placeholder: 'How was the recipe?' %>
            <%= f.input :rating, collection: [1,2,3,4,5] %>
            <%= f.submit "Review now", class: "btn-lg btn-warning" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>